In [2]:
import os, sys, time
import torch
import torch.nn as nn
import torchvision
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from torchvision import transforms

plt.rcParams["font.size"] = 12
plt.rcParams["figure.figsize"] = 6, 4

sns.set(rc={"figure.figsize": (6, 4)})
sns.set(style="darkgrid")

print("Numpy version:", np.version.version)

# Set working dir to project root
while not os.getcwd().endswith("lmc"):
    os.chdir(os.pardir)

Numpy version: 1.23.5


In [4]:
from src.models import SinkhornRebasinModel

rebasin_model = SinkhornRebasinModel(None, [5, 6, 7])
list(rebasin_model.parameters())

[Parameter containing:
 tensor([[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]], requires_grad=True),
 Parameter containing:
 tensor([[1., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 1.]], requires_grad=True),
 Parameter containing:
 tensor([[1., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 1.]], requires_grad=True)]

In [5]:
rebasin_model.state_dict()

OrderedDict([('permutations.0',
              tensor([[1., 0., 0., 0., 0.],
                      [0., 1., 0., 0., 0.],
                      [0., 0., 1., 0., 0.],
                      [0., 0., 0., 1., 0.],
                      [0., 0., 0., 0., 1.]])),
             ('permutations.1',
              tensor([[1., 0., 0., 0., 0., 0.],
                      [0., 1., 0., 0., 0., 0.],
                      [0., 0., 1., 0., 0., 0.],
                      [0., 0., 0., 1., 0., 0.],
                      [0., 0., 0., 0., 1., 0.],
                      [0., 0., 0., 0., 0., 1.]])),
             ('permutations.2',
              tensor([[1., 0., 0., 0., 0., 0., 0.],
                      [0., 1., 0., 0., 0., 0., 0.],
                      [0., 0., 1., 0., 0., 0., 0.],
                      [0., 0., 0., 1., 0., 0., 0.],
                      [0., 0., 0., 0., 1., 0., 0.],
                      [0., 0., 0., 0., 0., 1., 0.],
                      [0., 0., 0., 0., 0., 0., 1.]]))])